---
- name: Install core packages
  apt:
    name:
      - git
      - openssh-server
      - net-tools
      - nfs-common
      - python3
      - python3-pip
      - python3-venv
      - mysql-client
      - postgresql-client
    state: present
  become: true
