---
- name: Check if group 'apps' exists
  ansible.builtin.command: getent group apps
  register: group_exists
  ignore_errors: true

- name: Ensure the group 'apps' exists
  ansible.builtin.group:
    name: apps
    gid: 568
  become: true
  when: group_exists.rc != 0

- name: Check if user 'apps' exists
  ansible.builtin.command: id -u apps
  register: user_exists
  ignore_errors: true

- name: Ensure the user 'apps' exists with a specific UID
  ansible.builtin.user:
    name: apps
    uid: 568
    group: apps
    shell: /bin/bash
    create_home: no
  become: true
  when: user_exists.rc != 0

- name: Check if /mnt/epool directory exists
  ansible.builtin.stat:
    path: /mnt/epool
  register: epool_dir

- name: Create /mnt/epool directory if it does not exist
  ansible.builtin.file:
    path: /mnt/epool
    state: directory
    owner: apps
    group: apps
    mode: '0755'
  become: true
  when: not epool_dir.stat.exists

- name: Check if /mnt/epool/media directory exists
  ansible.builtin.stat:
    path: /mnt/epool/media
  register: epool_media_dir

- name: Create /mnt/epool/media directory if it does not exist
  ansible.builtin.file:
    path: /mnt/epool/media
    state: directory
    owner: apps
    group: apps
    mode: '0755'
  become: true
  when: not epool_media_dir.stat.exists

- name: Check if /mnt/epool/config directory exists
  ansible.builtin.stat:
    path: /mnt/epool/config
  register: epool_config_dir

- name: Create /mnt/epool/config directory if it does not exist
  ansible.builtin.file:
    path: /mnt/epool/config
    state: directory
    owner: apps
    group: apps
    mode: '0755'
  become: true
  when: not epool_config_dir.stat.exists

- name: Copy /mnt/workspace/fstab to /etc/fstab
  ansible.builtin.copy:
    src: /mnt/workspace/fstab
    dest: /etc/fstab
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Run "sudo mount -a"
  ansible.builtin.command: mount -a
  become: true