---
- name: Check if group 'apps' exists
  ansible.builtin.command: getent group apps
  register: group_exists
  ignore_errors: true

- name: Ensure the group 'apps' exists
  ansible.builtin.group:
    name: apps
    gid: 568
  become: true
  when: group_exists.rc != 0

- name: Check if user 'apps' exists
  ansible.builtin.command: id -u apps
  register: user_exists
  ignore_errors: true

- name: Ensure the user 'apps' exists with a specific UID
  ansible.builtin.user:
    name: apps
    uid: 568
    group: apps
    shell: /bin/bash
    create_home: no
  become: true
  when: user_exists.rc != 0

- name: Create /mnt/epool directory
  ansible.builtin.file:
    path: /mnt/epool
    state: directory
    owner: apps
    group: apps
    mode: '0755'
    creates: /mnt/epool
  become: true

- name: Create /mnt/epool/media directory
  ansible.builtin.file:
    path: /mnt/epool/media
    state: directory
    owner: apps
    group: apps
    mode: '0755'
    creates: /mnt/epool/media
  become: true

- name: Create /mnt/epool/config directory
  ansible.builtin.file:
    path: /mnt/epool/config
    state: directory
    owner: apps
    group: apps
    mode: '0755'
    creates: /mnt/epool/config
  become: true

- name: Copy /mnt/workspace/fstab to /etc/fstab
  ansible.builtin.copy:
    src: /mnt/workspace/fstab
    dest: /etc/fstab
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Run "sudo mount -a"
  ansible.builtin.command: mount -a
  become: true
