---
- name: Ensure the group 'apps' exists
  ansible.builtin.group:
    name: apps
    gid: 568

- name: Ensure the user 'apps' exists with a specific UID
  ansible.builtin.user:
    name: apps
    uid: 568
    group: apps
    shell: /bin/bash
    create_home: no