- name: Check Ansible temporary directory
  debug:
    var: ansible_env.TMPDIR

- name: Remove conflicting Docker and container-related packages
  apt:
    name: "{{ item }}"
    state: absent
  loop:
    - docker.io
    - docker-doc
    - docker-compose
    - docker-compose-v2
    - podman-docker
    - containerd
    - runc
  become: true

- name: Update the APT package index
  apt:
    update_cache: yes
  become: true

- name: Install ca-certificates and curl
  apt:
    name:
      - ca-certificates
      - curl
    state: present
  become: true

- name: Create /etc/apt/keyrings directory with specific permissions
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: true

- name: Verify Docker GPG key before download
  stat:
    path: /etc/apt/keyrings/docker.asc
  register: before_download

- name: Print before download status
  debug:
    var: before_download

- name: Download Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
  become: true

- name: Verify Docker GPG key after download
  stat:
    path: /etc/apt/keyrings/docker.asc
  register: after_download

- name: Print after download status
  debug:
    var: after_download

- name: Set read permissions for all users on Docker GPG key
  file:
    path: /etc/apt/keyrings/docker.asc
    mode: '0644'
  become: true

- name: Add Docker APT repository
  shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] \
    https://download.docker.com/linux/ubuntu \
    $(. /etc/os-release && echo $VERSION_CODENAME) stable" | \
    tee /etc/apt/sources.list.d/docker.list > /dev/null
  become: true

- name: Update the APT package index
  apt:
    update_cache: yes
  become: true

- name: Install Docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  become: true

- name: Add the current user to the docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  become: true

- name: Copy docker-compose.yaml to home directory
  copy:
    src: /mnt/workspace/docker-compose.yaml
    dest: "{{ compose_file_path }}"
    mode: '0644'
  become: true

- name: Stop Docker Compose
  shell: "docker compose -f {{ compose_file_path }} down"
  # args:
  #   chdir: "{{ compose_file_dir }}"
  become: true

- name: Start Docker Compose
  shell: "docker compose -f {{ compose_file_path }} up -d"
  # args:
  #   chdir: "{{ compose_file_dir }}"
  become: true