---
- name: Configure Terraform User
  hosts: all
  become: true
  tasks:
    - name: Add user
      ansible.builtin.user:
        name: terraform
        comment: "terraform"
        shell: /bin/bash
        uid: "1101"
        group: "1000"
        password: "$6$rounds=656000$.N95fLm9WxYyGGYx$D7XcWb7BLbqpDtU7GjQCCXLVlBvaxFhYWPgzY/J24cHNqVqcc7rvMdonMK76PP2PoWpvxQi8/op9uLwOk6aOO/"
